# This is a basic workflow to help you get started with Actions

name: V2FreeCheckIn

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * *' # UTC+8: 北京时间上午11点05分

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        user_list=()
        pwd_list=()

        IFS="," # 分隔符

        for u in ${user[*]}
        do
          user_list[${#user_list[*]}]=${u}
        done

        for p in ${pwd[*]}
        do
          pwd_list[${#pwd_list[*]}]=${p}
        done

        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}

        if [ $user_num != $pwd_num ];then
          echo "账号和密码个数不对应"
          exit 1
        else
          echo "共有 $user_num 个账号，开始签到！"
        fi

        for ((i=0;i<$user_num;i++))
        do
          python3 check_in.py --username ${user_list[$i]} --password ${pwd_list[$i]}
        done
    - name: Commit files
      run: |
        git config --global user.email 3356136957@qq.com
        git config --global user.name 签到机器人
        git add .
        git commit -m ":star: 签到成功" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
